spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}

service:
  ibm-watson-visual-recognition:
    URL: ${service.ibm-watson-visual-recognition.URL}
    APIKEY: ${service.ibm-watson-visual-recognition.APIKEY}